# Generated by Django 4.2.10 on 2024-04-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='اسم الباقة')),
            ],
            options={
                'verbose_name_plural': 'الباقة ',
            },
        ),
        migrations.CreateModel(
            name='Term_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100, verbose_name='القسم')),
                ('packege_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preset.packege', verbose_name=' الباقة')),
            ],
            options={
                'verbose_name_plural': '  الاقسام ',
            },
        ),
        migrations.CreateModel(
            name='Preset_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='البند')),
                ('term_title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preset.term_title', verbose_name=' القسم')),
            ],
            options={
                'verbose_name_plural': ' البنود المسبقة ',
            },
        ),
    ]
