# Generated by Django 4.2.10 on 2024-09-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packege',
            options={'verbose_name_plural': ' الباقات'},
        ),
        migrations.AlterField(
            model_name='preset_terms',
            name='term_title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preset.term_title', verbose_name=' التصنيف'),
        ),
        migrations.AlterField(
            model_name='term_title',
            name='section',
            field=models.CharField(max_length=100, verbose_name='التصنيفات'),
        ),
    ]
