# Generated by Django 4.2.10 on 2024-04-24 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cloudteam_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='الإدارة')),
            ],
            options={
                'verbose_name_plural': 'الإدارات',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100, verbose_name='رقم الجوال')),
                ('supervisor', models.BooleanField(default=0)),
                ('manager', models.BooleanField(default=0)),
                ('profile_img', models.FileField(null=True, upload_to='cloudtem/profile', verbose_name='الصورة الشخصية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
            options={
                'verbose_name_plural': 'الموظفين',
            },
        ),
        migrations.CreateModel(
            name='cloudteam_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='القسم')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudteam.cloudteam_department', verbose_name='الإدارة')),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudteam.employee', verbose_name='مشرف القسم')),
            ],
            options={
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.AddField(
            model_name='cloudteam_department',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudteam.employee', verbose_name='مدير الإدارة'),
        ),
    ]
