# Generated by Django 4.2.10 on 2024-04-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloudteam', '0001_initial'),
        ('clients', '0006_alter_branch_manager_id_alter_brand_gm_manager_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDate', models.DateField(null=True, verbose_name='تاريخ التسجيل')),
                ('bransh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.branch', verbose_name=' الفرغ')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudteam.employee', verbose_name='  المفتش')),
            ],
            options={
                'verbose_name_plural': 'طلب تقرير',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='البند')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.brand', verbose_name=' العلامة التجارية')),
            ],
            options={
                'verbose_name_plural': 'البند',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المكان')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.brand', verbose_name=' العلامة التجارية')),
            ],
            options={
                'verbose_name_plural': 'الأماكن',
            },
        ),
        migrations.CreateModel(
            name='Term_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100, verbose_name='الدرجة')),
                ('note', models.CharField(max_length=100, verbose_name='الملاحظة')),
                ('registerDate', models.DateField(null=True, verbose_name='تاريخ التسجيل')),
                ('report_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report_order', verbose_name=' طلب التقرير')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.term', verbose_name=' البند')),
            ],
            options={
                'verbose_name_plural': 'تقييم البنود',
            },
        ),
        migrations.CreateModel(
            name='Term_responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.section', verbose_name='  القسم المسؤول')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.term', verbose_name=' العلامة التجارية')),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.zone', verbose_name=' المكان')),
            ],
            options={
                'verbose_name_plural': 'مسؤولين البنود',
            },
        ),
        migrations.CreateModel(
            name='Score_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.CharField(max_length=100, verbose_name='الدرجة النهائية')),
                ('registerDate', models.DateField(null=True, verbose_name='تاريخ التسجيل')),
                ('report_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report_order', verbose_name=' طلب التقرير')),
            ],
            options={
                'verbose_name_plural': 'النتايج النهائية',
            },
        ),
    ]
