# Generated by Django 4.2.10 on 2024-05-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_term_responsible_term_id_alter_term_score_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='term_score',
            name='img',
            field=models.FileField(null=True, upload_to='customer/terms/Company/brand', verbose_name='المخالفة'),
        ),
    ]
