# Generated by Django 4.2.10 on 2024-09-03 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_managers_gm_manager'),
        ('report', '0004_term_score_quarter_term_score_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term_responsible',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.section', verbose_name='  القسم المسؤول'),
        ),
        migrations.AlterField(
            model_name='term_responsible',
            name='zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.zone', verbose_name=' المكان'),
        ),
    ]
