# Generated by Django 4.2.10 on 2024-09-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_term_responsible_section_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='cansel',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
