# Generated by Django 4.2.10 on 2024-09-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_term_cansel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='cansel',
            new_name='cancel',
        ),
    ]
