# Generated by Django 4.2.10 on 2024-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_rename_cansel_term_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_order',
            name='status',
            field=models.CharField(default='0', max_length=100, null=True, verbose_name='الحالة'),
        ),
    ]
