# Generated by Django 4.2.10 on 2024-10-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_report_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term_score',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='term_score',
            name='year',
        ),
        migrations.AddField(
            model_name='report_order',
            name='quarter',
            field=models.CharField(max_length=100, null=True, verbose_name='الربع'),
        ),
        migrations.AddField(
            model_name='report_order',
            name='year',
            field=models.CharField(max_length=100, null=True, verbose_name='السنه'),
        ),
    ]
