# Generated by Django 4.2.10 on 2024-10-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_company_packege'),
        ('report', '0009_remove_term_score_quarter_remove_term_score_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_history',
            name='quarter',
            field=models.CharField(max_length=100, null=True, verbose_name='الربع'),
        ),
        migrations.AddField(
            model_name='score_history',
            name='year',
            field=models.CharField(max_length=100, null=True, verbose_name='السنه'),
        ),
        migrations.CreateModel(
            name='Score_history_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.CharField(max_length=100, verbose_name='الدرجة النهائية')),
                ('quarter', models.CharField(max_length=100, null=True, verbose_name='الربع')),
                ('year', models.CharField(max_length=100, null=True, verbose_name='السنه')),
                ('registerDate', models.DateField(null=True, verbose_name='تاريخ التسجيل')),
                ('report_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report_order', verbose_name=' طلب التقرير')),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.section', verbose_name='  القسم ')),
            ],
            options={
                'verbose_name_plural': 'النتايج النهائية',
            },
        ),
    ]
