# Generated by Django 4.2.10 on 2024-10-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_score_history_quarter_score_history_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='note',
            field=models.CharField(max_length=1500, null=True, verbose_name='ملاحظات'),
        ),
    ]
