# Generated by Django 4.2.10 on 2024-04-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('logo', models.FileField(null=True, upload_to='customer/profile/Company/logo', verbose_name='الشعار')),
                ('registerDate', models.DateField(null=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='الإدارة')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name_plural': 'الإدارات',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'المدن'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'أحياء'},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='القسم')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.department', verbose_name='الإدارة')),
            ],
            options={
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='العلامة التجارية')),
                ('logo', models.FileField(null=True, upload_to='customer/profile/Company/brand', verbose_name='الشعار')),
                ('registerDate', models.DateField(null=True, verbose_name='تاريخ التسجيل')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name_plural': 'العلامات التجارية',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='الفرع')),
                ('registerDate', models.DateField(null=True, verbose_name='تاريخ التسجيل')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.brand', verbose_name='العلامة التجارية')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.district', verbose_name='العلامة التجارية')),
            ],
            options={
                'verbose_name_plural': 'الفروع',
            },
        ),
    ]
