# Generated by Django 4.2.10 on 2024-04-22 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_company_department_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.district', verbose_name='الحي'),
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100, verbose_name='رقم الجوال')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company', verbose_name='الشركة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
            options={
                'verbose_name_plural': 'المدراء',
            },
        ),
    ]
