# Generated by Django 4.2.10 on 2024-04-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_branch_district_id_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.managers', verbose_name='اسم المستخدم'),
        ),
    ]
