# Generated by Django 4.2.10 on 2024-04-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_brand_gm_manager_id_department_manager_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.managers', verbose_name='مدير فرع'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='gm_manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.managers', verbose_name='مدير عام العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='brand_citymanager',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.managers', verbose_name='مدير علامة تجارية'),
        ),
        migrations.AlterField(
            model_name='brand_regionmanager',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.managers', verbose_name='مدير علامة تجارية'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.managers', verbose_name='مدير الإدارة'),
        ),
        migrations.AlterField(
            model_name='section',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.managers', verbose_name='مدير القسم'),
        ),
    ]
