# Generated by Django 4.2.10 on 2024-08-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_managers_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managers',
            name='task_traker',
        ),
        migrations.AddField(
            model_name='section',
            name='Brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.brand', verbose_name='العلامة التجارية'),
        ),
    ]
