# Generated by Django 4.2.10 on 2024-09-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preset', '0002_alter_packege_options_and_more'),
        ('clients', '0009_remove_managers_gm_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='packege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preset.packege', verbose_name=' المدينة'),
        ),
    ]
