# Generated by Django 4.2.10 on 2025-02-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preset', '0002_alter_packege_options_and_more'),
        ('clients', '0010_company_packege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='packege',
        ),
        migrations.AddField(
            model_name='brand',
            name='packege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preset.packege', verbose_name=' الباقة'),
        ),
    ]
